name: Deploy to Shared Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 36.50.77.79
          username: orzverse
          port: 64000
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            bash ~/deploy.sh
